### ISSUE TITLE
Shared libraries

### ISSUE THREAD

**Issue by melrobin** [math-atlas/math-atlas#15]
New versions of ATLAS do not build the shared libraries.  Here are some of the errors:
/usr/bin/ld: cannot find rpath-link /usr/local/atlas/lib: No such file or directory
libatlas.a(ATL_cherk_amm.o): In function `syrk_K':
ATL_syrk_amm.c:(.text+0x6f0): multiple definition of`syrk_K'
libatlas.a(ATL_zherk_amm.o):ATL_syrk_amm.c:(.text+0x6f0): first defined here
libatlas.a(ATL_ztammm_G.o): In function `DoLastComp':
ATL_tammm_G.c:(.text+0x830): multiple definition of`DoLastComp'
libatlas.a(ATL_dtammm_G.o):ATL_tammm_G.c:(.text+0x670): first defined here
libatlas.a(ATL_ctammm_G.o): In function `DoLastComp':
ATL_tammm_G.c:(.text+0x830): multiple definition of`DoLastComp'
libatlas.a(ATL_dtammm_G.o):ATL_tammm_G.c:(.text+0x670): first defined here
libatlas.a(ATL_stammm_G.o): In function `DoLastComp':
ATL_tammm_G.c:(.text+0x670): multiple definition of`DoLastComp'
libatlas.a(ATL_dtammm_G.o):ATL_tammm_G.c:(.text+0x670): first defined here
collect2: error: ld returned 1 exit status
Makefile:126: recipe for target 'GCCTRY' failed
make[7]: **\* [GCCTRY] Error 1
make[7]: Leaving directory '/home/melrobin/packages/math-atlas/TEST/ATLAS/build/lib'
make[7]: Entering directory '/home/melrobin/packages/math-atlas/TEST/ATLAS/build/lib'
ld -melf_x86_64 -shared -soname /usr/local/atlas/lib/libsatlas.so -o libsatlas.so \
           -rpath-link /usr/local/atlas/lib  \
           --whole-archive liblapack.a libf77blas.a libcblas.a libatlas.a --no-whole-archive -L/usr/lib/gcc/x86_64-redhat-linux/5.3.1 -lgfortran  -lc -lpthread -lm -lgcc
libatlas.a(ATL_cherk_amm.o): In function `syrk_K':
ATL_syrk_amm.c:(.text+0x6f0): multiple definition of`syrk_K'
libatlas.a(ATL_zherk_amm.o):ATL_syrk_amm.c:(.text+0x6f0): first defined here
libatlas.a(ATL_ztammm_G.o): In function `DoLastComp':
ATL_tammm_G.c:(.text+0x830): multiple definition of`DoLastComp'
libatlas.a(ATL_dtammm_G.o):ATL_tammm_G.c:(.text+0x670): first defined here
libatlas.a(ATL_ctammm_G.o): In function `DoLastComp':
ATL_tammm_G.c:(.text+0x830): multiple definition of`DoLastComp'
libatlas.a(ATL_dtammm_G.o):ATL_tammm_G.c:(.text+0x670): first defined here
libatlas.a(ATL_stammm_G.o): In function `DoLastComp':
ATL_tammm_G.c:(.text+0x670): multiple definition of`DoLastComp'
libatlas.a(ATL_dtammm_G.o):ATL_tammm_G.c:(.text+0x670): first defined here
Makefile:122: recipe for target 'LDTRY' failed
make[7]: **\* [LDTRY] Error 1

**Comment by rcwhaley** [comment]
Please post help requests:
http://math-atlas.sourceforge.net/faq.html#help
