### ISSUE TITLE
`configure --help` fails trying to compile `xconfig`

### ISSUE THREAD

**Issue by matthew-brett** [math-atlas/math-atlas#3]
Looking at the configure script, it seems that `configure --help` should be expected to work.

However, if you run `configure --help` in a bare directory, you get the expected help from configure, followed by:

```
Attempting to build xconfig to get probe flags:
../ATLAS/configure: line 113: ./xconfig: No such file or directory
```

This is because configure is trying to build xconfig without any of the files needed to do this yet being in the current directory.

`configure -help` (one hyphen for `-help`) doesn't give the expected help from the `configure` script, but does give the expected help from the `xconfig` binary. This is because the bad argument (`-help`) passes further through the script before the script detects that the argument is not recognized, and therefore does copy in the needed files to build the `xconfig` binary.

Maybe the machinery to build the `xconfig` binary could get copied in a subroutine in the sh script and this used to build xconfig in the branch detecting `--help` as an input argument?

**Comment by rcwhaley** [comment]
I'm closing this because I believe I fixed it long ago, open again if you disagree.
